# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1354806897);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1354807017);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1354806777);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1354658312);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1354807137);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.manager.showWhenStarting", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 7);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 2);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.buildID", "20121129165506");
user_pref("browser.startup.homepage_override.mstone", "17.0.1");
user_pref("browser.startup.page", 0);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.disable_open_during_load", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "firebug%40software.joehewitt.com:1.7.3,globalmenu%40ubuntu.com:3.6.4,ubufox%40ubuntu.com:2.6,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:17.0.1");
user_pref("extensions.enabledItems", "firebug@software.joehewitt.com:1.7.3,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.28");
user_pref("extensions.firebug.addonBarOpened", true);
user_pref("extensions.firebug.allPagesActivation", "on");
user_pref("extensions.firebug.console.enableSites", true);
user_pref("extensions.firebug.currentVersion", "1.7.3");
user_pref("extensions.firebug.defaultPanelName", "console");
user_pref("extensions.firebug.net.enableSites", true);
user_pref("extensions.firebug.script.enableSites", true);
user_pref("extensions.firebug.showCSSErrors", true);
user_pref("extensions.firebug.toolbarCustomizationDone", true);
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1353937839000}}},{\"name\":\"app-global\",\"addons\":{\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox/extensions/globalmenu@ubuntu.com\",\"mtime\":1354630334000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1354630335000}}},{\"name\":\"app-profile\",\"addons\":{\"firebug@software.joehewitt.com\":{\"descriptor\":\"/home/brianb/code/trisano/webapp/features/support/firefox-36-profile/extensions/firebug@software.joehewitt.com\",\"mtime\":1354702399000}}}]");
user_pref("extensions.lastAppVersion", "17.0.1");
user_pref("extensions.lastPlatformVersion", "17.0.1");
user_pref("extensions.newAddons", false);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("layout.spellcheckDefault", 0);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.soname.list", "");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.warn_entering_weak", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("signon.rememberSignons", false);
user_pref("toolkit.startup.last_success", 1354806773);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1357250110);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
user_pref("xpinstall.whitelist.required", false);
