# Copyright (C) 2007, 2008, 2009 The Collaborative Software Foundation
#
# This file is part of TriSano.
#
# TriSano is free software: you can redistribute it and/or modify it under the 
# terms of the GNU Affero General Public License as published by the 
# Free Software Foundation, either version 3 of the License, 
# or (at your option) any later version.
#
# TriSano is distributed in the hope that it will be useful, but 
# WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License 
# along with TriSano. If not, see http://www.gnu.org/licenses/agpl-3.0.txt.

 class FkIndexes < ActiveRecord::Migration
def self.up 
  #  add_index(:accounts, [:branch_id, :party_id], :unique => true)
add_index (:telephones 		, :location_id)
add_index (:people_races	, :race_id)
add_index (:people_races	, :entity_id)
add_index (:referrals		, :event_id)
add_index (:treatments		, :treatment_type_id)
add_index (:participations_treatments  , :participation_id)
add_index (:participations_treatments  , :treatment_id)
add_index (:participations_treatments  , :treatment_given_yn_id)
add_index (:materials		, :entity_id)
add_index (:observations	, :event_id)
add_index (:entity_groups	, :primary_entity_id)
add_index (:entity_groups	, :secondary_entity_id)
add_index (:entity_groups	, :entity_group_type_id)
add_index (:hospitals_participations	, :participation_id)	
add_index (:cases_events	, :event_id)
add_index (:clusters		, :primary_event_id)
add_index (:clusters		, :secondary_event_id)
add_index (:clusters		, :cluster_status_id)
add_index (:encounters		, :event_id)
#add_index (:addresses		, :city_id)
add_index (:addresses		, :county_id)
#add_index (:addresses		, :district_id)
add_index (:addresses		, :location_id)
add_index (:addresses		, :state_id)
add_index (:animals		, :entity_id)
add_index (:places		, :entity_id)
add_index (:places		, :place_type_id)
add_index (:participations_risk_factors	, :participation_id)
add_index (:participations_risk_factors	, :food_handler_id)
add_index (:participations_risk_factors	, :healthcare_worker_id)
add_index (:participations_risk_factors	, :group_living_id)
add_index (:participations_risk_factors	, :day_care_association_id)
add_index (:participations_risk_factors	, :pregnant_id)
add_index (:disease_events	, :event_id)
add_index (:disease_events	, :disease_id)
add_index (:disease_events	, :hospitalized_id)
add_index (:disease_events	, :died_id)
add_index (:people		, :entity_id)
add_index (:people		, :birth_gender_id)
#add_index (:people		, :current_gender_id)
add_index (:people		, :ethnicity_id)
add_index (:people		, :primary_language_id)
add_index (:people		, :age_type_id)
#add_index (:people		, :people_type_id)
add_index (:people		, :first_name_soundex)
add_index (:people		, :last_name_soundex)
#add_index (:events		, :event_type_id)
add_index (:events		, :event_status_id)
add_index (:events		, :imported_from_id)
add_index (:events		, :event_case_status_id)
add_index (:events		, :outbreak_associated_id)
add_index (:events		, :investigation_LHD_status_id)
add_index (:lab_results		, :specimen_source_id)
add_index (:lab_results		, :tested_at_uphl_yn_id)
#add_index (:lab_results		, :participation_id)
add_index (:participations	, :primary_entity_id)
add_index (:participations	, :secondary_entity_id)
add_index (:participations	, :role_id)
add_index (:participations	, :participation_status_id)
add_index (:participations	, :event_id)
end

def self.down
remove_index (:telephones 		, :location_id)
remove_index (:people_races	, :race_id)
remove_index (:people_races	, :entity_id)
remove_index (:referrals		, :event_id)
remove_index (:treatments		, :treatment_type_id)
remove_index (:participations_treatments  , :participation_id)
remove_index (:participations_treatments  , :treatment_id)
remove_index (:participations_treatments  , :treatment_given_yn_id)
remove_index (:materials		, :entity_id)
remove_index (:observations	, :event_id)
remove_index (:entity_groups	, :primary_entity_id)
remove_index (:entity_groups	, :secondary_entity_id)
remove_index (:entity_groups	, :entity_group_type_id)
remove_index (:hospitals_participations	, :participation_id)	
remove_index (:cases_events	, :event_id)
remove_index (:clusters		, :primary_event_id)
remove_index (:clusters		, :secondary_event_id)
remove_index (:clusters		, :cluster_status_id)
remove_index (:encounters		, :event_id)
#remove_index (:addresses		, :city_id)
remove_index (:addresses		, :county_id)
#remove_index (:addresses		, :district_id)
remove_index (:addresses		, :location_id)
remove_index (:addresses		, :state_id)
remove_index (:animals		, :entity_id)
remove_index (:places		, :entity_id)
remove_index (:places		, :place_type_id)
remove_index (:participations_risk_factors	, :participation_id)
remove_index (:participations_risk_factors	, :food_handler_id)
remove_index (:participations_risk_factors	, :healthcare_worker_id)
remove_index (:participations_risk_factors	, :group_living_id)
remove_index (:participations_risk_factors	, :day_care_association_id)
remove_index (:participations_risk_factors	, :pregnant_id)
remove_index (:disease_events	, :event_id)
remove_index (:disease_events	, :disease_id)
remove_index (:disease_events	, :hospitalized_id)
remove_index (:disease_events	, :died_id)
remove_index (:people		, :entity_id)
remove_index (:people		, :birth_gender_id)
#remove_index (:people		, :current_gender_id)
remove_index (:people		, :ethnicity_id)
remove_index (:people		, :primary_language_id)
remove_index (:people		, :age_type_id)
#remove_index (:people		, :people_type_id)
remove_index (:people		, :first_name_soundex)
remove_index (:people		, :last_name_soundex)
#remove_index (:events		, :event_type_id)
remove_index (:events		, :event_status_id)
remove_index (:events		, :imported_from_id)
remove_index (:events		, :event_case_status_id)
remove_index (:events		, :outbreak_associated_id)
remove_index (:events		, :investigation_LHD_status_id)
remove_index (:lab_results		, :specimen_source_id)
remove_index (:lab_results		, :tested_at_uphl_yn_id)
#remove_index (:lab_results		, :participation_id)
remove_index (:participations	, :primary_entity_id)
remove_index (:participations	, :secondary_entity_id)
remove_index (:participations	, :role_id)
remove_index (:participations	, :participation_status_id)
remove_index (:participations	, :event_id)  
end

end
