# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
# Triggering a build

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

# Added for ci_reporter
require 'rubygems'
gem 'ci_reporter'
require 'ci/reporter/rake/rspec' # use for RSpec
require 'ci/reporter/rake/test_unit' # for Test::Unit
