# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
# Triggering a build

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

# Added for ci_reporter
require 'rubygems'
gem 'ci_reporter'
require 'ci/reporter/rake/rspec' # use for RSpec
require 'ci/reporter/rake/test_unit' # for Test::Unit
    
Rake::Task["db:structure:dump"].enhance {
  abcs = ActiveRecord::Base.configurations
  ENV['PGHOST']     = abcs[RAILS_ENV]["host"] if abcs[RAILS_ENV]["host"]
  ENV['PGPORT']     = abcs[RAILS_ENV]["port"].to_s if abcs[RAILS_ENV]["port"]
  ENV['PGPASSWORD'] = abcs[RAILS_ENV]["password"].to_s if abcs[RAILS_ENV]["password"]
  search_path = abcs[RAILS_ENV]["schema_search_path"]
  search_path = "--schema=#{search_path}" if search_path
  `pg_dump -i -U "#{abcs[RAILS_ENV]["username"]}" --data-only -x -O -f db/#{RAILS_ENV}_pg_ts_contents.sql #{search_path} #{abcs[RAILS_ENV]["database"]} --table=pg_ts_cfg --table=pg_ts_dict --table=pg_ts_parser --table=pg_ts_cfgmap`
  raise "Error dumping Postgres full text contents" if $?.exitstatus == 1
}

Rake::Task["db:test:clone_structure"].enhance {
  abcs = ActiveRecord::Base.configurations
  ENV['PGHOST']     = abcs["test"]["host"] if abcs["test"]["host"]
  ENV['PGPORT']     = abcs["test"]["port"].to_s if abcs["test"]["port"]
  ENV['PGPASSWORD'] = abcs["test"]["password"].to_s if abcs["test"]["password"]
  `psql -U "#{abcs["test"]["username"]}" -f db/#{RAILS_ENV}_pg_ts_contents.sql #{abcs["test"]["database"]}`
  
  # Rake::Task["nedss:dev:update_test_locale_config"].invoke
  `psql -U "#{abcs["test"]["username"]}" -c \"UPDATE pg_ts_cfg SET LOCALE = current_setting('lc_collate') WHERE ts_name = 'default'\" #{abcs["test"]["database"]}`
  
  raise "Error loading Postgres full text contents" if $?.exitstatus == 1
}

Rake::Task["db:create:all"].enhance {
  Rake::Task["nedss:dev:add_tsearch"].invoke
  Rake::Task["nedss:dev:update_locale_configs"].invoke
}

# The following could be a bit more dry/dynamic
Rake::Task["db:create"].enhance {
  case ENV['RAILS_ENV']
  when "development"
    Rake::Task["nedss:dev:add_tsearch_to_dev"].invoke
    Rake::Task["nedss:dev:update_dev_locale_config"].invoke
  when "test"
    Rake::Task["nedss:dev:add_tsearch_to_test"].invoke
    Rake::Task["nedss:dev:update_test_locale_config"].invoke
  else
    raise "tsearch not installed in this environment -- only dev and test supported"
  end
}
