postgres_dir: /usr/bin # Location of Postgres client
host: localhost # PostgreSQL host server 
port: 5432 # PostgreSQL TCP listen port 
environment: production # the name of the environment - corresponds to rails configuration
basicauth: false # whether HTTP basic auth should be on
database: trisano_development # Database name
priv_uname: placey # Database privileged username (used for upgrade db script)
priv_passwd: while(1); # Privileged user's password (used for upgrade db script)
trisano_uname: nedss # trisano application username (used by package app script)
trisano_user_passwd: password # trisano application user password (used by package app script)
min_runtimes: 2 # minimum number of trisano runtimes 
max_runtimes: 5 # maximum number of trisano runtimes 
runtime_timeout: 5 # number of seconds that web app thread should wait before generating HTTP 503 and informing user to try again
dump_file_name: nedss_prod-01-20-2009.dump_obfu # assumes dump file is in the ./dump directory - example trisano_production-09-25-2008-1123AM.dump
support_url: # the URL of the TriSano Support system. Defaults to http://www.trisano.org/collaborate/ 

