-- Ideally we'd have the foreign keys described here, but foreign keys to
-- system tables aren't allowed

CREATE TABLE trisano.core_tables (
    table_name NAME PRIMARY KEY,
    table_description TEXT,
    target_table TEXT NOT NULL, -- The actual table name this should point at
    order_num INTEGER NOT NULL,
    make_category BOOLEAN DEFAULT true
);

CREATE TABLE trisano.core_columns (
    target_column NAME,
    target_table TEXT, -- The actual table this column belongs in
    PRIMARY KEY (target_column, target_table),
    column_name TEXT,
    column_description TEXT,
    make_category_column BOOLEAN DEFAULT true
);

INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_morbidity_events_view', 'Morbidity Events', 'trisano.dw_morbidity_events_view',1);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_morbidity_clinicians_view', 'Morbidity Clinicians', 'trisano.dw_morbidity_clinicians_view',2);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_morbidity_diagnostic_facilities_view', 'Morbidity Diagnostic Facilities', 'trisano.dw_morbidity_diagnostic_facilities_view',3);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_morbidity_diseases_view', 'Morbidity Diseases', 'trisano.dw_morbidity_diseases_view',4);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_morbidity_hospitals_view', 'Morbidity Hospitals', 'trisano.dw_morbidity_hospitals_view',5);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_morbidity_lab_results_view', 'Morbidity Lab Results', 'trisano.dw_morbidity_lab_results_view',6);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_morbidity_patients_view', 'Morbidity Patients', 'trisano.dw_morbidity_patients_view',7);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_morbidity_patients_races_view', 'Morbidity Patients Races', 'trisano.dw_morbidity_patients_races_view',8);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_morbidity_reporting_agencies_view', 'Morbidity Reporting Agencies', 'trisano.dw_morbidity_reporting_agencies_view',9);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_morbidity_reporters_view', 'Morbidity Reporters', 'trisano.dw_morbidity_reporters_view',10);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_morbidity_secondary_jurisdictions_view', 'Morbidity Secondary Jurisdictions', 'trisano.dw_morbidity_secondary_jurisdictions_view',11);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_morbidity_treatments_events_view', 'Morbidity Treatments Events', 'trisano.dw_morbidity_treatments_events_view',12);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_contact_events_view', 'Contact Events', 'trisano.dw_contact_events_view',13);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_contact_clinicians_view', 'Contact Clinicians', 'trisano.dw_contact_clinicians_view',14);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_contact_diagnostic_facilities_view', 'Contact Diagnostic Facilities', 'trisano.dw_contact_diagnostic_facilities_view',15);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_contact_diseases_view', 'Contact Diseases', 'trisano.dw_contact_diseases_view',16);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_contact_hospitals_view', 'Contact Hospitals', 'trisano.dw_contact_hospitals_view',17);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_contact_lab_results_view', 'Contact Lab Results', 'trisano.dw_contact_lab_results_view',18);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_contact_patients_view', 'Contact Patients', 'trisano.dw_contact_patients_view',19);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_contact_patients_races_view', 'Contact Patients Races', 'trisano.dw_contact_patients_races_view',20);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_contact_secondary_jurisdictions_view', 'Contact Secondary Jurisdictions', 'trisano.dw_contact_secondary_jurisdictions_view',21);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_contact_treatments_events_view', 'Contact Treatments Events', 'trisano.dw_contact_treatments_events_view',22);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_encounters_view', 'Encounters', 'trisano.dw_encounters_view',23);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_encounters_lab_results_view', 'Encounters Lab Results', 'trisano.dw_encounters_lab_results_view',24);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_encounters_treatments_events_view', 'Encounters Treatments Events', 'trisano.dw_encounters_treatments_events_view',25);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'dw_place_events_view', 'Place Events', 'trisano.dw_place_events_view',26);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (true,  'avr_groups_view', 'Disease Groups', 'trisano.avr_groups_view',27);
INSERT INTO trisano.core_tables (make_category, table_name,table_description,target_table,order_num) VALUES (false, 'avr_groups_diseases_view', 'avr_groups_diseases_view', 'trisano.avr_groups_diseases_view',28);

INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('race', 'trisano.dw_morbidity_patients_races_view', 'race', 'Morbidity Patients Race', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('first_name', 'trisano.dw_morbidity_clinicians_view', 'first_name', 'Morbidity Clinicians First Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('treatment_lead_in', 'trisano.dw_contact_diseases_view', 'treatment_lead_in', 'Contact Diseases Treatment Lead-in', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_investigation_started', 'trisano.dw_morbidity_events_view', 'date_investigation_started', 'Morbidity Events Date Investigation Started', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_investigation_completed', 'trisano.dw_morbidity_events_view', 'date_investigation_completed', 'Morbidity Events Date Investigation Completed', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('jurisdiction_of_residence', 'trisano.dw_morbidity_events_view', 'jurisdiction_of_residence', 'Morbidity Events Jurisdiction of Residence', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('estimated_age_at_onset', 'trisano.dw_morbidity_events_view', 'estimated_age_at_onset', 'Morbidity Events Estimated Age at Onset', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('additional_risk_factors', 'trisano.dw_morbidity_events_view', 'additional_risk_factors', 'Morbidity Events Additional Risk Factors', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('street_number', 'trisano.dw_morbidity_events_view', 'street_number', 'Morbidity Events Street Number', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_disease_diagnosed', 'trisano.dw_morbidity_events_view', 'date_disease_diagnosed', 'Morbidity Events Date Disease Diagnosed', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_morbidity_lab_results_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_encounter_events_id', 'trisano.dw_morbidity_lab_results_view', 'dw_encounter_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('person_id', 'trisano.dw_contact_patients_races_view', 'person_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('investigating_jurisdiction_id', 'trisano.dw_morbidity_events_view', 'investigating_jurisdiction_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_encounters_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_morbidity_clinicians_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('middle_name', 'trisano.dw_morbidity_patients_view', 'middle_name', 'Morbidity Patients Middle Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('middle_name', 'trisano.dw_contact_patients_view', 'middle_name', 'Contact Patients Middle Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('investigating_jurisdiction', 'trisano.dw_contact_events_view', 'investigating_jurisdiction', 'Contact Events Investigating Jurisdiction', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('group_living', 'trisano.dw_contact_events_view', 'group_living', 'Contact Events Group Living', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('other_data_2', 'trisano.dw_contact_events_view', 'other_data_2', 'Contact Events Other Data 2', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_disease_onset', 'trisano.dw_contact_events_view', 'date_disease_onset', 'Contact Events Date Disease Onset', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('review_completed_by_state_date', 'trisano.dw_contact_events_view', 'review_completed_by_state_date', 'Contact Events Review Completed by State', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('middle_name', 'trisano.dw_morbidity_reporters_view', 'middle_name', 'Morbidity Reporters Middle Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_of_treatment', 'trisano.dw_contact_treatments_events_view', 'date_of_treatment', 'Contact Treatments Events Date of Treatment', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('result_value', 'trisano.dw_morbidity_lab_results_view', 'result_value', 'Morbidity Lab Results Result Value', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('collection_date', 'trisano.dw_contact_lab_results_view', 'collection_date', 'Contact Lab Results Collection Date', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('test_status', 'trisano.dw_contact_lab_results_view', 'test_status', 'Contact Lab Results Test Status', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_place_events_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_place_events_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_encounters_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('encounter_event_id', 'trisano.dw_encounters_view', 'encounter_event_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('created_at', 'trisano.avr_groups_view', 'created_at', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('updated_at', 'trisano.avr_groups_view', 'updated_at', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.avr_groups_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_morbidity_diseases_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_contact_diseases_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('avr_group_id', 'trisano.avr_groups_diseases_view', 'avr_group_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('updated_at', 'trisano.avr_groups_diseases_view', 'updated_at', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('created_at', 'trisano.avr_groups_diseases_view', 'created_at', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('disease_id', 'trisano.dw_morbidity_events_view', 'disease_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('disease_id', 'trisano.avr_groups_diseases_view', 'disease_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_morbidity_events_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_patients_id', 'trisano.dw_morbidity_events_view', 'dw_patients_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('parent_id', 'trisano.dw_morbidity_events_view', 'parent_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('jurisdiction_of_residence_id', 'trisano.dw_morbidity_events_view', 'jurisdiction_of_residence_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_deleted', 'trisano.dw_morbidity_events_view', 'date_deleted', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('imported_from_code', 'trisano.dw_morbidity_events_view', 'imported_from_code', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('always_one', 'trisano.dw_morbidity_events_view', 'always_one', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('event_queue_id', 'trisano.dw_morbidity_events_view', 'event_queue_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('first_name_soundex', 'trisano.dw_morbidity_patients_view', 'first_name_soundex', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_morbidity_patients_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('entity_id', 'trisano.dw_morbidity_patients_view', 'entity_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('last_name_soundex', 'trisano.dw_morbidity_patients_view', 'last_name_soundex', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_contact_patients_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('entity_id', 'trisano.dw_contact_patients_view', 'entity_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('last_name_soundex', 'trisano.dw_contact_patients_view', 'last_name_soundex', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_contact_events_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_patients_id', 'trisano.dw_contact_events_view', 'dw_patients_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('parent_id', 'trisano.dw_contact_events_view', 'parent_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('disease_id', 'trisano.dw_contact_events_view', 'disease_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('investigating_jurisdiction_id', 'trisano.dw_contact_events_view', 'investigating_jurisdiction_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('jurisdiction_of_residence_id', 'trisano.dw_contact_events_view', 'jurisdiction_of_residence_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_updated', 'trisano.dw_contact_events_view', 'date_updated', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_created', 'trisano.dw_contact_events_view', 'date_created', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('event_queue_id', 'trisano.dw_contact_events_view', 'event_queue_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_deleted', 'trisano.dw_contact_events_view', 'date_deleted', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('imported_from_code', 'trisano.dw_contact_events_view', 'imported_from_code', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('always_one', 'trisano.dw_contact_events_view', 'always_one', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_contact_events_id', 'trisano.dw_morbidity_reporting_agencies_view', 'dw_contact_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_morbidity_patients_races_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_contact_patients_races_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('place_id', 'trisano.dw_morbidity_reporting_agencies_view', 'place_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_morbidity_reporting_agencies_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_morbidity_reporting_agencies_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_contact_events_id', 'trisano.dw_morbidity_diagnostic_facilities_view', 'dw_contact_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('place_id', 'trisano.dw_morbidity_diagnostic_facilities_view', 'place_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_morbidity_diagnostic_facilities_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_morbidity_diagnostic_facilities_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_contact_events_id', 'trisano.dw_contact_diagnostic_facilities_view', 'dw_contact_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('place_id', 'trisano.dw_contact_diagnostic_facilities_view', 'place_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_contact_diagnostic_facilities_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_encounter_events_id', 'trisano.dw_morbidity_treatments_events_view', 'dw_encounter_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_morbidity_reporters_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_contact_diagnostic_facilities_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_morbidity_reporters_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_contact_events_id', 'trisano.dw_morbidity_reporters_view', 'dw_contact_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_contact_events_id', 'trisano.dw_morbidity_treatments_events_view', 'dw_contact_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_morbidity_treatments_events_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('treatment_id', 'trisano.dw_morbidity_treatments_events_view', 'treatment_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_morbidity_treatments_events_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_encounter_events_id', 'trisano.dw_contact_treatments_events_view', 'dw_encounter_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_contact_treatments_events_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_contact_events_id', 'trisano.dw_contact_treatments_events_view', 'dw_contact_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('treatment_id', 'trisano.dw_contact_treatments_events_view', 'treatment_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_encounters_treatments_events_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_contact_treatments_events_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_encounter_events_id', 'trisano.dw_encounters_treatments_events_view', 'dw_encounter_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_contact_events_id', 'trisano.dw_encounters_treatments_events_view', 'dw_contact_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('treatment_id', 'trisano.dw_encounters_treatments_events_view', 'treatment_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_morbidity_lab_results_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_encounters_treatments_events_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_contact_lab_results_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_encounter_events_id', 'trisano.dw_contact_lab_results_view', 'dw_encounter_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_contact_events_id', 'trisano.dw_contact_lab_results_view', 'dw_contact_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_contact_lab_results_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_encounters_lab_results_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_contact_events_id', 'trisano.dw_encounters_lab_results_view', 'dw_contact_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_encounter_events_id', 'trisano.dw_encounters_lab_results_view', 'dw_encounter_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_contact_events_id', 'trisano.dw_contact_hospitals_view', 'dw_contact_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_contact_hospitals_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_morbidity_secondary_jurisdictions_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_contact_events_id', 'trisano.dw_morbidity_secondary_jurisdictions_view', 'dw_contact_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('jurisdiction_id', 'trisano.dw_morbidity_secondary_jurisdictions_view', 'jurisdiction_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_morbidity_secondary_jurisdictions_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_contact_secondary_jurisdictions_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('jurisdiction_id', 'trisano.dw_contact_secondary_jurisdictions_view', 'jurisdiction_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_contact_secondary_jurisdictions_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('last_name', 'trisano.dw_morbidity_clinicians_view', 'last_name', 'Morbidity Clinicians Last Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('middle_name', 'trisano.dw_morbidity_clinicians_view', 'middle_name', 'Morbidity Clinicians Middle Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('middle_name', 'trisano.dw_contact_clinicians_view', 'middle_name', 'Contact Clinicians Middle Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('first_name', 'trisano.dw_contact_clinicians_view', 'first_name', 'Contact Clinicians Last Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('last_name', 'trisano.dw_contact_clinicians_view', 'last_name', 'Contact Clinicians Last Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('postal_code', 'trisano.dw_place_events_view', 'postal_code', 'Place Events Postal Code', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('name', 'trisano.dw_place_events_view', 'name', 'Place Events Place Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('place_type', 'trisano.dw_place_events_view', 'place_type', 'Place Events Place Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('street_number', 'trisano.dw_place_events_view', 'street_number', 'Place Events Street Number', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('street_name', 'trisano.dw_place_events_view', 'street_name', 'Place Events Street Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('unit_number', 'trisano.dw_place_events_view', 'unit_number', 'Place Events Unit Number', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('city', 'trisano.dw_place_events_view', 'city', 'Place Events City', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('state', 'trisano.dw_place_events_view', 'state', 'Place Events State', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('county', 'trisano.dw_place_events_view', 'county', 'Place Events County', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('latitude', 'trisano.dw_place_events_view', 'latitude', 'Place Events Latitude', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('longitude', 'trisano.dw_place_events_view', 'longitude', 'Place Events Longitude', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('description', 'trisano.dw_encounters_view', 'description', 'Encounter Description', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('investigator_id', 'trisano.dw_encounters_view', 'investigator_id', 'Encounter Investigator', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('encounter_date', 'trisano.dw_encounters_view', 'encounter_date', 'Encounter Date', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('location', 'trisano.dw_encounters_view', 'location', 'Encounter Location', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('name', 'trisano.avr_groups_view', 'name', 'Disease Group Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('treatment_lead_in', 'trisano.dw_morbidity_diseases_view', 'treatment_lead_in', 'Morbidity Diseases Treatment Lead-In', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_contact_clinicians_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('place_lead_in', 'trisano.dw_morbidity_diseases_view', 'place_lead_in', 'Morbidity Diseases Place Lead-in', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('contact_lead_in', 'trisano.dw_morbidity_diseases_view', 'contact_lead_in', 'Morbidity Diseases Contact Lead-in', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('cdc_code', 'trisano.dw_morbidity_diseases_view', 'cdc_code', 'Morbidity Diseases CDC Code', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('active', 'trisano.dw_morbidity_diseases_view', 'active', 'Morbidity Diseases Active', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('disease_name', 'trisano.dw_morbidity_diseases_view', 'disease_name', 'Morbidity Diseases Disease Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('contact_lead_in', 'trisano.dw_contact_diseases_view', 'contact_lead_in', 'Contact Diseases Contact Lead-in', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('cdc_code', 'trisano.dw_contact_diseases_view', 'cdc_code', 'Contact Diseases CDC Code', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('active', 'trisano.dw_contact_diseases_view', 'active', 'Contact Diseases Active', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('disease_name', 'trisano.dw_contact_diseases_view', 'disease_name', 'Contact Diseases Disease Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('place_lead_in', 'trisano.dw_contact_diseases_view', 'place_lead_in', 'Contact Diseases Place Lead-in', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('investigating_jurisdiction', 'trisano.dw_morbidity_events_view', 'investigating_jurisdiction', 'Morbidity Events Investigating Jurisdiction', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('state_case_status_code', 'trisano.dw_morbidity_events_view', 'state_case_status_code', 'Morbidity Events State Case Status Code', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('lhd_case_status_code', 'trisano.dw_morbidity_events_view', 'lhd_case_status_code', 'Morbidity Events LHD Case Status Code', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_contact_events_id', 'trisano.dw_contact_clinicians_view', 'dw_contact_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('review_completed_by_state_date', 'trisano.dw_morbidity_events_view', 'review_completed_by_state_date', 'Morbidity Events Date Review Completed by State', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('sent_to_cdc', 'trisano.dw_morbidity_events_view', 'sent_to_cdc', 'Morbidity Events Sent to CDC', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('contact_type_if_once_a_contact', 'trisano.dw_morbidity_events_view', 'contact_type_if_once_a_contact', 'Morbidity Events Contact Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('disposition_if_once_a_contact', 'trisano.dw_morbidity_events_view', 'disposition_if_once_a_contact', 'Morbidity Events Disposition', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('sent_to_ibis', 'trisano.dw_morbidity_events_view', 'sent_to_ibis', 'Morbidity Events Sent to IBIS', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('ibis_updated_at', 'trisano.dw_morbidity_events_view', 'ibis_updated_at', 'Morbidity Events Date IBIS Updated', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_created', 'trisano.dw_morbidity_events_view', 'date_created', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('disease_event_died', 'trisano.dw_morbidity_events_view', 'disease_event_died', 'Morbidity Events Died', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_updated', 'trisano.dw_morbidity_events_view', 'date_updated', 'Morbidity Events Date Updated', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('pregnancy_due_date', 'trisano.dw_morbidity_events_view', 'pregnancy_due_date', 'Morbidity Events Pregnancy Due Date', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('risk_factor_details', 'trisano.dw_morbidity_events_view', 'risk_factor_details', 'Morbidity Events Risk Factor Details', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('last_name', 'trisano.dw_contact_patients_view', 'last_name', 'Contact Patients Last Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('birth_date', 'trisano.dw_contact_patients_view', 'birth_date', 'Contact Patients Birth Date', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_of_death', 'trisano.dw_contact_patients_view', 'date_of_death', 'Contact Patients Date of Death', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('street_name', 'trisano.dw_contact_events_view', 'street_name', 'Contact Events Street Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('actual_age_at_onset', 'trisano.dw_contact_events_view', 'actual_age_at_onset', 'Contact Events Actual Age at Onset', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('first_name_soundex', 'trisano.dw_contact_patients_view', 'first_name_soundex', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('jurisdiction_of_residence', 'trisano.dw_contact_events_view', 'jurisdiction_of_residence', 'Contact Events Jurisdiction of Residence', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('actual_age_type', 'trisano.dw_contact_events_view', 'actual_age_type', 'Contact Events Actual Age Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('age_in_years', 'trisano.dw_contact_events_view', 'age_in_years', 'Contact Events Age in Years', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('estimated_age_at_onset', 'trisano.dw_contact_events_view', 'estimated_age_at_onset', 'Contact Events Estimated Age at Onset', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('estimated_age_type', 'trisano.dw_contact_events_view', 'estimated_age_type', 'Contact Events Estimated Age Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('food_handler', 'trisano.dw_contact_events_view', 'food_handler', 'Contact Events Food Handler', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('healthcare_worker', 'trisano.dw_contact_events_view', 'healthcare_worker', 'Contact Events Healthcare Worker', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('day_care_association', 'trisano.dw_contact_events_view', 'day_care_association', 'Contact Events Day Care Association', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('race', 'trisano.dw_contact_patients_races_view', 'race', 'Contact Patients Race', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('person_id', 'trisano.dw_morbidity_patients_races_view', 'person_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('name', 'trisano.dw_morbidity_reporting_agencies_view', 'name', 'Morbidity Reporting Agencies Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('place_type', 'trisano.dw_morbidity_reporting_agencies_view', 'place_type', 'Morbidity Reporting Agencies Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('name', 'trisano.dw_morbidity_diagnostic_facilities_view', 'name', 'Morbidity Diagnostic Facilities Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('place_type', 'trisano.dw_morbidity_diagnostic_facilities_view', 'place_type', 'Morbidity Diagnostic Facilities Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('name', 'trisano.dw_contact_diagnostic_facilities_view', 'name', 'Contact Diagnostic Facilities Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('place_type', 'trisano.dw_contact_diagnostic_facilities_view', 'place_type', 'Contact Diagnostic Facilities Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('last_name', 'trisano.dw_morbidity_reporters_view', 'last_name', 'Morbidity Reporters Last Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('first_name', 'trisano.dw_morbidity_reporters_view', 'first_name', 'Morbidity Reporters First Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('treatment_given', 'trisano.dw_morbidity_treatments_events_view', 'treatment_given', 'Morbidity Treatments Events Treatment Given', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_of_treatment', 'trisano.dw_morbidity_treatments_events_view', 'date_of_treatment', 'Morbidity Treatments Events Date of Treatment', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('treatment_notes', 'trisano.dw_morbidity_treatments_events_view', 'treatment_notes', 'Morbidity Treatments Events Treatment Notes', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('treatment_given', 'trisano.dw_contact_treatments_events_view', 'treatment_given', 'Contact Treatments Events Treatment Given', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('treatment_notes', 'trisano.dw_contact_treatments_events_view', 'treatment_notes', 'Contact Treatments Events Treatment Notes', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('treatment_given', 'trisano.dw_encounters_treatments_events_view', 'treatment_given', 'Encounters Treatments Events Treatment Given', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_of_treatment', 'trisano.dw_encounters_treatments_events_view', 'date_of_treatment', 'Encounters Treatments Events Date of Treatment', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('treatment_notes', 'trisano.dw_encounters_treatments_events_view', 'treatment_notes', 'Encounters Treatments Events Treatment Notes', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_encounters_lab_results_view', 'id', 'Encounters Lab Results ', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('specimen_source', 'trisano.dw_morbidity_lab_results_view', 'specimen_source', 'Morbidity Lab Results Specimen Source', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('collection_date', 'trisano.dw_morbidity_lab_results_view', 'collection_date', 'Morbidity Lab Results Collection Date', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('lab_test_date', 'trisano.dw_morbidity_lab_results_view', 'lab_test_date', 'Morbidity Lab Results Lab Test Date', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('specimen_sent_to_state', 'trisano.dw_morbidity_lab_results_view', 'specimen_sent_to_state', 'Morbidity Lab Results Specimen Sent to State', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('reference_range', 'trisano.dw_morbidity_lab_results_view', 'reference_range', 'Morbidity Lab Results Reference Range', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('loinc_code', 'trisano.dw_morbidity_lab_results_view', 'loinc_code', 'Morbidity Lab Results LOINC code', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('test_type', 'trisano.dw_morbidity_lab_results_view', 'test_type', 'Morbidity Lab Results Test Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_contact_events_id', 'trisano.dw_morbidity_lab_results_view', 'dw_contact_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_contact_events_id', 'trisano.dw_contact_secondary_jurisdictions_view', 'dw_contact_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_morbidity_clinicians_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_morbidity_hospitals_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_contact_events_id', 'trisano.dw_morbidity_hospitals_view', 'dw_contact_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('id', 'trisano.dw_morbidity_hospitals_view', 'id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('dw_morbidity_events_id', 'trisano.dw_contact_hospitals_view', 'dw_morbidity_events_id', '', false);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('name', 'trisano.dw_encounters_lab_results_view', 'name', 'Encounters Lab Results Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('lab_type', 'trisano.dw_encounters_lab_results_view', 'lab_type', 'Encounters Lab Results Lab Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('hl7_message', 'trisano.dw_encounters_lab_results_view', 'hl7_message', 'Encounters Lab Results HL7 Message', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('staged_message_state', 'trisano.dw_encounters_lab_results_view', 'staged_message_state', 'Encounters Lab Results Staged Message State', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('staged_message_note', 'trisano.dw_encounters_lab_results_view', 'staged_message_note', 'Encounters Lab Results Staged Message Note', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('hospital_name', 'trisano.dw_morbidity_hospitals_view', 'hospital_name', 'Morbidity Hospitals Hospital Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('admission_date', 'trisano.dw_morbidity_hospitals_view', 'admission_date', 'Morbidity Hospitals Admission Date', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('discharge_date', 'trisano.dw_morbidity_hospitals_view', 'discharge_date', 'Morbidity Hospitals Discharge Date', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('medical_record_number', 'trisano.dw_morbidity_hospitals_view', 'medical_record_number', 'Morbidity Hospitals Medical Record Number', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('hospital_record_number', 'trisano.dw_morbidity_hospitals_view', 'hospital_record_number', 'Morbidity Hospitals Hospital Record Number', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('hospital_name', 'trisano.dw_contact_hospitals_view', 'hospital_name', 'Contact Hospitals Hospital Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('admission_date', 'trisano.dw_contact_hospitals_view', 'admission_date', 'Contact Hospitals Admission Date', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('discharge_date', 'trisano.dw_contact_hospitals_view', 'discharge_date', 'Contact Hospitals Discharge DAte', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('medical_record_number', 'trisano.dw_contact_hospitals_view', 'medical_record_number', 'Contact Hospitals Medical Record Number', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('hospital_record_number', 'trisano.dw_contact_hospitals_view', 'hospital_record_number', 'Contact Hospitals Hospital Record Number', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('name', 'trisano.dw_morbidity_secondary_jurisdictions_view', 'name', 'Morbidity Secondary Jurisdictions Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('name', 'trisano.dw_contact_secondary_jurisdictions_view', 'name', 'Contact Secondary Jurisdictions Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('collection_date', 'trisano.dw_encounters_lab_results_view', 'collection_date', 'Encounters Lab Results Collection Date', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('mmwr_week', 'trisano.dw_morbidity_events_view', 'mmwr_week', 'Morbidity Events MMWR Week', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('mmwr_year', 'trisano.dw_morbidity_events_view', 'mmwr_year', 'Morbidity Events MMWR Year', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('event_name', 'trisano.dw_morbidity_events_view', 'event_name', 'Morbidity Events Event Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('record_number', 'trisano.dw_morbidity_events_view', 'record_number', 'Morbidity Events Record Number', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('actual_age_at_onset', 'trisano.dw_morbidity_events_view', 'actual_age_at_onset', 'Morbidity Events Actual Age at Onset', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('actual_age_type', 'trisano.dw_morbidity_events_view', 'actual_age_type', 'Morbidity Events Actual Age Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('age_in_years', 'trisano.dw_morbidity_events_view', 'age_in_years', 'Morbidity Events Age in Years', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('estimated_age_type', 'trisano.dw_morbidity_events_view', 'estimated_age_type', 'Morbidity Events Estimated Age Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('parent_guardian', 'trisano.dw_morbidity_events_view', 'parent_guardian', 'Morbidity Events Parent/Guardian', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('food_handler', 'trisano.dw_morbidity_events_view', 'food_handler', 'Morbidity Events Food Handler', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('healthcare_worker', 'trisano.dw_morbidity_events_view', 'healthcare_worker', 'Morbidity Events Healthcare Worker', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('group_living', 'trisano.dw_morbidity_events_view', 'group_living', 'Morbidity Events Group Living', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('day_care_association', 'trisano.dw_morbidity_events_view', 'day_care_association', 'Morbidity Events Day Care Association', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('pregnant', 'trisano.dw_morbidity_events_view', 'pregnant', 'Morbidity Events Pregnant', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('occupation', 'trisano.dw_morbidity_events_view', 'occupation', 'Morbidity Events Occupation', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('other_data_1', 'trisano.dw_morbidity_events_view', 'other_data_1', 'Morbidity Events Other Data 1', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('disease_event_hospitalized', 'trisano.dw_morbidity_events_view', 'disease_event_hospitalized', 'Morbidity Events Hospitalized', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('other_data_2', 'trisano.dw_morbidity_events_view', 'other_data_2', 'Morbidity Events Other Data 2', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('outbreak_associated_code', 'trisano.dw_morbidity_events_view', 'outbreak_associated_code', 'Morbidity Events Outbreak Associated Code', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('outbreak_name', 'trisano.dw_morbidity_events_view', 'outbreak_name', 'Morbidity Events Outbreak Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('investigator', 'trisano.dw_morbidity_events_view', 'investigator', 'Morbidity Events Investigator', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('acuity', 'trisano.dw_morbidity_events_view', 'acuity', 'Morbidity Events Acuity', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('street_name', 'trisano.dw_morbidity_events_view', 'street_name', 'Morbidity Events Street Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('unit_number', 'trisano.dw_morbidity_events_view', 'unit_number', 'Morbidity Events Unit Number', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('city', 'trisano.dw_morbidity_events_view', 'city', 'Morbidity Events City', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('county', 'trisano.dw_morbidity_events_view', 'county', 'Morbidity Events County', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('state', 'trisano.dw_morbidity_events_view', 'state', 'Morbidity Events State', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('postal_code', 'trisano.dw_morbidity_events_view', 'postal_code', 'Morbidity Events Postal Code', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('latitude', 'trisano.dw_morbidity_events_view', 'latitude', 'Morbidity Events Latitude', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('longitude', 'trisano.dw_morbidity_events_view', 'longitude', 'Morbidity Events Longitude', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_disease_onset', 'trisano.dw_morbidity_events_view', 'date_disease_onset', 'Morbidity Events Date Disease Onset', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('results_reported_to_clinician_date', 'trisano.dw_morbidity_events_view', 'results_reported_to_clinician_date', 'Morbidity Events Results Reported to Clinician', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_reported_to_public_health', 'trisano.dw_morbidity_events_view', 'date_reported_to_public_health', 'Morbidity Events Date Reported to Public Health', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_entered_into_system', 'trisano.dw_morbidity_events_view', 'date_entered_into_system', 'Morbidity Events Date Entered Into System', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('birth_gender', 'trisano.dw_morbidity_patients_view', 'birth_gender', 'Morbidity Patients Birth Gender', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('ethnicity', 'trisano.dw_morbidity_patients_view', 'ethnicity', 'Morbidity Patients Ethnicity', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('primary_language', 'trisano.dw_morbidity_patients_view', 'primary_language', 'Morbidity Patients Primary Language', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('first_name', 'trisano.dw_morbidity_patients_view', 'first_name', 'Morbidity Patients First Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('last_name', 'trisano.dw_morbidity_patients_view', 'last_name', 'Morbidity Patients Last Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('birth_date', 'trisano.dw_morbidity_patients_view', 'birth_date', 'Morbidity Patients Birth Date', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_of_death', 'trisano.dw_morbidity_patients_view', 'date_of_death', 'Morbidity Patients Date of Death', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('birth_gender', 'trisano.dw_contact_patients_view', 'birth_gender', 'Contact Patients Birth Gender', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('ethnicity', 'trisano.dw_contact_patients_view', 'ethnicity', 'Contact Patients Ethnicity', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('primary_language', 'trisano.dw_contact_patients_view', 'primary_language', 'Contact Patients Primary Language', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('first_name', 'trisano.dw_contact_patients_view', 'first_name', 'Contact Patients First Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('pregnant', 'trisano.dw_contact_events_view', 'pregnant', 'Contact Events Pregnant', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('pregnancy_due_date', 'trisano.dw_contact_events_view', 'pregnancy_due_date', 'Contact Events Pregnancy Due Date', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('additional_risk_factors', 'trisano.dw_contact_events_view', 'additional_risk_factors', 'Contact Events Additional Risk Factors', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('risk_factor_details', 'trisano.dw_contact_events_view', 'risk_factor_details', 'Contact Events Risk Factor Details', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('occupation', 'trisano.dw_contact_events_view', 'occupation', 'Contact Events Occupation', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('other_data_1', 'trisano.dw_contact_events_view', 'other_data_1', 'Contact Events Other Data 1', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('disease_event_hospitalized', 'trisano.dw_contact_events_view', 'disease_event_hospitalized', 'Contact Events Hospitalized', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('investigator', 'trisano.dw_contact_events_view', 'investigator', 'Contact Events Investigator', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('street_number', 'trisano.dw_contact_events_view', 'street_number', 'Contact Events Street Number', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('unit_number', 'trisano.dw_contact_events_view', 'unit_number', 'Contact Events Unit Number', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('city', 'trisano.dw_contact_events_view', 'city', 'Contact Events City', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('county', 'trisano.dw_contact_events_view', 'county', 'Contact Events County', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('state', 'trisano.dw_contact_events_view', 'state', 'Contact Events State', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('postal_code', 'trisano.dw_contact_events_view', 'postal_code', 'Contact Events Postal Code', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('latitude', 'trisano.dw_contact_events_view', 'latitude', 'Contact Events Latitude', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('longitude', 'trisano.dw_contact_events_view', 'longitude', 'Contact Events Longitude', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_disease_diagnosed', 'trisano.dw_contact_events_view', 'date_disease_diagnosed', 'Contact Events Date Disease Diagnosed', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_entered_into_system', 'trisano.dw_contact_events_view', 'date_entered_into_system', 'Contact Events Date Entered Into System', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_investigation_started', 'trisano.dw_contact_events_view', 'date_investigation_started', 'Contact Events Date Investigation Started', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('date_investigation_completed', 'trisano.dw_contact_events_view', 'date_investigation_completed', 'Contact Events Date Investigation Completed', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('disposition', 'trisano.dw_contact_events_view', 'disposition', 'Contact Events Disposition', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('contact_type', 'trisano.dw_contact_events_view', 'contact_type', 'Contact Events Contact Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('sent_to_ibis', 'trisano.dw_contact_events_view', 'sent_to_ibis', 'Contact Events Sent to IBIS', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('ibis_updated_at', 'trisano.dw_contact_events_view', 'ibis_updated_at', 'Contact Events IBIS Updated', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('disease_event_died', 'trisano.dw_contact_events_view', 'disease_event_died', 'Contact Events Died', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('test_result', 'trisano.dw_morbidity_lab_results_view', 'test_result', 'Morbidity Lab Results Test Result', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('units', 'trisano.dw_morbidity_lab_results_view', 'units', 'Morbidity Lab Results Units', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('test_status', 'trisano.dw_morbidity_lab_results_view', 'test_status', 'Morbidity Lab Results Test Status', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('comment', 'trisano.dw_morbidity_lab_results_view', 'comment', 'Morbidity Lab Results Comment', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('name', 'trisano.dw_morbidity_lab_results_view', 'name', 'Morbidity Lab Results Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('lab_type', 'trisano.dw_morbidity_lab_results_view', 'lab_type', 'Morbidity Lab Results Lab Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('hl7_message', 'trisano.dw_morbidity_lab_results_view', 'hl7_message', 'Morbidity Lab Results HL7 Message', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('staged_message_state', 'trisano.dw_morbidity_lab_results_view', 'staged_message_state', 'Morbidity Lab Results Staged Message State', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('staged_message_note', 'trisano.dw_morbidity_lab_results_view', 'staged_message_note', 'Morbidity Lab Results Staged Message Note', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('specimen_source', 'trisano.dw_contact_lab_results_view', 'specimen_source', 'Contact Lab Results Specimen Source', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('lab_test_date', 'trisano.dw_contact_lab_results_view', 'lab_test_date', 'Contact Lab Results Lab Test Date', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('specimen_sent_to_state', 'trisano.dw_contact_lab_results_view', 'specimen_sent_to_state', 'Contact Lab Results Specimen Sent to State', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('reference_range', 'trisano.dw_contact_lab_results_view', 'reference_range', 'Contact Lab Results Reference Range', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('loinc_code', 'trisano.dw_contact_lab_results_view', 'loinc_code', 'Contact Lab Results LOINC Code', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('test_type', 'trisano.dw_contact_lab_results_view', 'test_type', 'Contact Lab Results Test Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('test_result', 'trisano.dw_contact_lab_results_view', 'test_result', 'Contact Lab Results Test Result', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('result_value', 'trisano.dw_contact_lab_results_view', 'result_value', 'Contact Lab Results Result Value', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('units', 'trisano.dw_contact_lab_results_view', 'units', 'Contact Lab Results Units', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('comment', 'trisano.dw_contact_lab_results_view', 'comment', 'Contact Lab Results Comment', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('name', 'trisano.dw_contact_lab_results_view', 'name', 'Contact Lab Results Name', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('lab_type', 'trisano.dw_contact_lab_results_view', 'lab_type', 'Contact Lab Results Lab Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('hl7_message', 'trisano.dw_contact_lab_results_view', 'hl7_message', 'Contact Lab Results HL7 Message', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('staged_message_state', 'trisano.dw_contact_lab_results_view', 'staged_message_state', 'Contact Lab Results Staged Message State', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('staged_message_note', 'trisano.dw_contact_lab_results_view', 'staged_message_note', 'Contact Lab Results Staged Message Note', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('lab_test_date', 'trisano.dw_encounters_lab_results_view', 'lab_test_date', 'Encounters Lab Results Lab Test Date', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('specimen_source', 'trisano.dw_encounters_lab_results_view', 'specimen_source', 'Encounters Lab Results Specimen Source', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('specimen_sent_to_state', 'trisano.dw_encounters_lab_results_view', 'specimen_sent_to_state', 'Encounters Lab Results Specimen Sent to State', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('reference_range', 'trisano.dw_encounters_lab_results_view', 'reference_range', 'Encounters Lab Results Reference Range', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('loinc_code', 'trisano.dw_encounters_lab_results_view', 'loinc_code', 'Encounters Lab Results LOINC Code', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('test_type', 'trisano.dw_encounters_lab_results_view', 'test_type', 'Encounters Lab Results Test Type', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('test_result', 'trisano.dw_encounters_lab_results_view', 'test_result', 'Encounters Lab Results Test Result', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('result_value', 'trisano.dw_encounters_lab_results_view', 'result_value', 'Encounters Lab Results Result Value', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('units', 'trisano.dw_encounters_lab_results_view', 'units', 'Encounters Lab Results Units', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('test_status', 'trisano.dw_encounters_lab_results_view', 'test_status', 'Encounters Lab Results Test Status', true);
INSERT INTO trisano.core_columns (target_column, target_table, column_name, column_description, make_category_column) VALUES ('comment', 'trisano.dw_encounters_lab_results_view', 'comment', 'Encounters Lab Results Comment', true);

CREATE TABLE trisano.core_relationships (
    from_column NAME NOT NULL,
    from_table TEXT NOT NULL,
    to_column NAME NOT NULL,
    to_table TEXT NOT NULL,
    relation_type TEXT DEFAULT '1:N'
);

INSERT INTO trisano.core_relationships (from_table, from_column, to_table, to_column, relation_type) VALUES 
('dw_encounters_view'               , 'id'                , 'dw_encounters_lab_results_view'            , 'dw_encounter_events_id' , '1:N'),
('dw_encounters_view'               , 'id'                , 'dw_encounters_treatments_events_view'      , 'dw_encounter_events_id' , '1:N'),
('dw_morbidity_events_view'         , 'dw_patients_id'    , 'dw_morbidity_patients_view'                , 'id'                     , '1:1'),
('dw_morbidity_patients_races_view' , 'person_id'         , 'dw_morbidity_patients_view'                , 'id'                     , 'N:1'),
('dw_morbidity_events_view'         , 'id'                , 'dw_morbidity_clinicians_view'              , 'dw_morbidity_events_id' , '1:N'),
('dw_morbidity_events_view'         , 'id'                , 'dw_morbidity_diagnostic_facilities_view'   , 'dw_morbidity_events_id' , '1:N'),
('dw_morbidity_events_view'         , 'id'                , 'dw_morbidity_hospitals_view'               , 'dw_morbidity_events_id' , '1:N'),
('dw_morbidity_events_view'         , 'id'                , 'dw_morbidity_lab_results_view'             , 'dw_morbidity_events_id' , '1:N'),
('dw_morbidity_events_view'         , 'id'                , 'dw_morbidity_reporters_view'               , 'dw_morbidity_events_id' , '1:N'),
('dw_morbidity_events_view'         , 'id'                , 'dw_morbidity_reporting_agencies_view'      , 'dw_morbidity_events_id' , '1:N'),
('dw_morbidity_events_view'         , 'id'                , 'dw_contact_events_view'                    , 'parent_id'              , '1:N'),
('dw_contact_events_view'           , 'id'                , 'dw_contact_diagnostic_facilities_view'     , 'dw_contact_events_id'   , '1:N'),
('dw_contact_events_view'           , 'id'                , 'dw_contact_clinicians_view'                , 'dw_contact_events_id'   , '1:N'),
('dw_contact_events_view'           , 'dw_patients_id'    , 'dw_contact_patients_view'                  , 'id'                     , '1:1'),
('dw_contact_patients_races_view'   , 'person_id'         , 'dw_contact_patients_view'                  , 'id'                     , 'N:1'),
('dw_contact_events_view'           , 'id'                , 'dw_contact_hospitals_view'                 , 'dw_contact_events_id'   , '1:N'),
('dw_contact_events_view'           , 'id'                , 'dw_contact_lab_results_view'               , 'dw_contact_events_id'   , '1:N'),
('dw_morbidity_events_view'         , 'id'                , 'dw_morbidity_treatments_events_view'       , 'dw_morbidity_events_id' , '1:N'),
('dw_contact_events_view'           , 'id'                , 'dw_contact_treatments_events_view'         , 'dw_contact_events_id'   , '1:N'),
('dw_morbidity_events_view'         , 'disease_id'        , 'dw_morbidity_diseases_view'                , 'id'                     , '1:1'),
('dw_contact_events_view'           , 'disease_id'        , 'dw_contact_diseases_view'                  , 'id'                     , '1:1'),
('dw_morbidity_events_view'         , 'id'                , 'dw_encounters_view'                        , 'dw_morbidity_events_id' , '1:N'),
('dw_morbidity_events_view'         , 'id'                , 'dw_place_events_view'                      , 'dw_morbidity_events_id' , '1:N'),
('dw_contact_events_view'           , 'id'                , 'dw_contact_secondary_jurisdictions_view'   , 'dw_contact_events_id'   , '1:N'),
('dw_morbidity_events_view'         , 'id'                , 'dw_morbidity_secondary_jurisdictions_view' , 'dw_morbidity_events_id' , '1:N');
