source "http://gems.github.com"
source "http://rubygems.org"
gem "rails", "2.3.5"

platforms :jruby do
  gem "activerecord-jdbcpostgresql-adapter", "= 1.0.0.kofnopre1"
  gem "jruby-openssl", "= 0.7.2"
end

platforms :ruby_18, :ruby_19 do
  gem "pg"
end

gem "logging"
gem "rails_inheritable_attributes_manager"
gem "haml", "2.0.7"
gem "validates_timeliness", ">= 2.2.2"
gem "mislav-will_paginate"
gem "rubyzip"
gem "delayed_job", '~>2.0.7'

gem "ruby-hl7", "1.0.3"

# Need to put this in it's place soon. It's getting cocky standing out
# on its own like this.
gem "sparrowhawk", "0.9.5"

group :development do
  gem "mechanize"
  gem "rest-open-uri"
  gem "ci_reporter"
  gem "hirb"
  gem "capistrano"
  gem "capistrano-ext"
  gem "ruby-debug"
  gem "rails-footnotes", '< 3.7.0'
end

group :test, :development do
  gem "mongrel"
  platforms :ruby_18, :ruby_19 do
    gem "unicorn"
  end
  gem "watchr", :require => false
end

group :test, :uattest do
  gem "rspec-rails"
  gem "mocha"
  gem "faker"
  gem "factory_girl"
  gem "cucumber", "0.6.3"
  gem "cucumber-rails", "0.3.0"
  gem "webrat", "= 0.7.2.pre"
  gem "database_cleaner"
  gem "selenium-client"
end
