source "http://gems.github.com"
source "http://rubygems.org"
gem "rails", "2.3.5"

platforms :jruby do
  gem "activerecord-jdbcpostgresql-adapter", :path => '~/projects/activerecord-jdbc-adapter/adapters/postgresql'
  gem "jruby-openssl"
  group :cli do
    gem "warbler"
  end
end

platforms :ruby_18, :ruby_19 do
  gem "pg"
end

gem "logging"
gem "rails_inheritable_attributes_manager"
gem "haml", "2.0.7"
gem "ruby-hl7"
gem "validates_timeliness", ">= 2.2.2"
gem "mislav-will_paginate"
gem "rubyzip"

group :development do
  gem "mechanize"
  gem "rest-open-uri"
  gem "ci_reporter"
end

group :test, :devlopment do
  gem "mongrel"
end

group :test, :uattest do
  gem "rspec-rails"
  gem "mocha"
  gem "faker"
  gem "factory_girl"
  gem "cucumber", "0.6.3"
  gem "cucumber-rails", "0.3.0"
  gem "webrat", :git => "git://github.com/kofno/webrat.git"
  gem "database_cleaner"
  gem "selenium-client"
end

gem "wirble", :group => :cli
