# Copyright (C) 2007, 2008, The Collaborative Software Foundation
#
# This file is part of TriSano.
#
# TriSano is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# TriSano is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with TriSano. If not, see http://www.gnu.org/licenses/agpl-3.0.txt.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

# Added for ci_reporter
require 'rubygems'
gem 'ci_reporter'
require 'ci/reporter/rake/rspec' # use for RSpec
require 'ci/reporter/rake/test_unit' # for Test::Unit

Rake::Task["db:test:prepare"].enhance {
  #TODO: Rake::Task["db:seed"].invoke
  ruby "-S rake db:seed RAILS_ENV=test"
  ruby "-S rake spec:db:fixtures:load FIXTURES=codes,code_translations,external_codes,external_code_translations RAILS_ENV=test"
}

Dir["#{RAILS_ROOT}/vendor/trisano/*/tasks/**/*.rake"].sort.each { |ext| load ext }
Dir["#{RAILS_ROOT}/vendor/trisano/*/lib/tasks/**/*.rake"].sort.each { |ext| load ext }
