 COMMENT ON SCHEMA population IS 'Schema for OLAP population and rate calculation data';
 COMMENT ON TABLE population.population_dimensions IS 'Describes each of the OLAP dimensions usable for population calculation';
 COMMENT ON COLUMN population.population_dimensions.dim_name IS 'Names of each OLAP dimension for which population divisions are known';
 COMMENT ON COLUMN population.population_dimensions.dim_cols IS 'Column names to be searched for population counts. Each array element corresponds to a different level of the dimension hierarchy';
 COMMENT ON COLUMN population.population_dimensions.mapping_func IS 'Functions to map OLAP values to something the underlying population tables will understand. Each element correspond to a level of the dimension hierarchy';
 COMMENT ON TABLE population.population_tables IS 'Records the tables in the population schema that record population information';
 COMMENT ON COLUMN population.population_tables.table_name IS 'Name of the population table';
 COMMENT ON COLUMN population.population_tables.table_rank IS 'When multiple tables will provide the required information, this rank is used to find the desired table. Lowest ranks are selected first (e.g. the table with rank 1 is the best one to use, all else being equal';
 COMMENT ON SCHEMA public IS 'Staging area for data warehouse ETL process';
 COMMENT ON SCHEMA trisano IS 'Contains views used for reporting and OLAP ';
 COMMENT ON VIEW trisano.addresses_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.answers_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.attachments_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.cdc_exports_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.codes_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.core_fields_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.csv_fields_view IS 'data dictionary ignore';
 COMMENT ON TABLE trisano.current_schema_name IS 'Internal -- used so ETL process knows which schema can be dumped and reloaded';
 COMMENT ON COLUMN trisano.current_schema_name.schemaname IS 'Contains the name of the schema currently in use by the warehouse, and referenced by all the views';
 COMMENT ON VIEW trisano.db_files_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.disease_events_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.diseases_export_columns_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.diseases_external_codes_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.diseases_forms_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.diseases_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.dw_contact_answers_view IS 'Formbuilder answers applicable to contact events. See transactional database, answers table for more information';
 COMMENT ON COLUMN trisano.dw_contact_answers_view.code IS '';
 COMMENT ON VIEW trisano.dw_contact_clinicians_view IS 'Clinician information applicable to contact events';
 COMMENT ON COLUMN trisano.dw_contact_clinicians_view.dw_contact_events_id IS 'The contact event ID this answer refers to';
 COMMENT ON COLUMN trisano.dw_contact_clinicians_view.first_name IS '';
 COMMENT ON COLUMN trisano.dw_contact_clinicians_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_contact_clinicians_view.last_name IS '';
 COMMENT ON COLUMN trisano.dw_contact_clinicians_view.middle_name IS '';
 COMMENT ON VIEW trisano.dw_contact_diagnostic_facilities_view IS 'Diagnostic facility information applicable to contact events';
 COMMENT ON COLUMN trisano.dw_contact_diagnostic_facilities_view.dw_contact_events_id IS 'The contact event ID this answer refers to';
 COMMENT ON COLUMN trisano.dw_contact_diagnostic_facilities_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_contact_diagnostic_facilities_view.name IS 'Name of the diagnostic facility';
 COMMENT ON COLUMN trisano.dw_contact_diagnostic_facilities_view.place_id IS 'Places table record related to this record';
 COMMENT ON COLUMN trisano.dw_contact_diagnostic_facilities_view.place_type IS 'Type of facility';
 COMMENT ON VIEW trisano.dw_contact_diseases_view IS 'Diseases related to contact events. See diseases table for more information';
 COMMENT ON COLUMN trisano.dw_contact_diseases_view.active IS '';
 COMMENT ON COLUMN trisano.dw_contact_diseases_view.cdc_code IS '';
 COMMENT ON COLUMN trisano.dw_contact_diseases_view.contact_lead_in IS '';
 COMMENT ON COLUMN trisano.dw_contact_diseases_view.disease_name IS '';
 COMMENT ON COLUMN trisano.dw_contact_diseases_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_contact_diseases_view.place_lead_in IS '';
 COMMENT ON COLUMN trisano.dw_contact_diseases_view.treatment_lead_in IS '';
 COMMENT ON VIEW trisano.dw_contact_events_view IS 'Table of contact events. Most fields match the events table';
 COMMENT ON COLUMN trisano.dw_contact_events_view.actual_age_at_onset IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.actual_age_type IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.additional_risk_factors IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.age_in_years IS 'Calculated age in years, based on actual_age_at_onset and actual_age_type';
 COMMENT ON COLUMN trisano.dw_contact_events_view.city IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.contact_type IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.county IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.date_created IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.date_deleted IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.date_disease_diagnosed IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.date_disease_onset IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.date_entered_into_system IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.date_investigation_completed IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.date_investigation_started IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.date_updated IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.day_care_association IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.disease_event_died IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.disease_event_hospitalized IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.disease_id IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.disposition IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.dw_patients_id IS 'ID of patient record related to this event';
 COMMENT ON COLUMN trisano.dw_contact_events_view.estimated_age_at_onset IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.estimated_age_type IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.event_queue_id IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.food_handler IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.group_living IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.healthcare_worker IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.ibis_updated_at IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_contact_events_view.imported_from_code IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.investigating_jurisdiction IS 'Name of the investigating jurisdiction';
 COMMENT ON COLUMN trisano.dw_contact_events_view.investigating_jurisdiction_id IS 'Places table record for this investigating jurisdiction';
 COMMENT ON COLUMN trisano.dw_contact_events_view.investigator IS 'Name of investigator';
 COMMENT ON COLUMN trisano.dw_contact_events_view.jurisdiction_of_residence IS 'Name of jurisdiction of residence';
 COMMENT ON COLUMN trisano.dw_contact_events_view.jurisdiction_of_residence_id IS 'Places table record for this jurisdiction of residence';
 COMMENT ON COLUMN trisano.dw_contact_events_view.latitude IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.longitude IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.occupation IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.other_data_1 IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.other_data_2 IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.parent_id IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.postal_code IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.pregnancy_due_date IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.pregnant IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.review_completed_by_state_date IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.risk_factor_details IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.sent_to_ibis IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.state IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.street_name IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.street_number IS '';
 COMMENT ON COLUMN trisano.dw_contact_events_view.unit_number IS '';
 COMMENT ON VIEW trisano.dw_contact_hospitals_view IS 'Information about hospital admissions related to contact events';
 COMMENT ON COLUMN trisano.dw_contact_hospitals_view.admission_date IS '';
 COMMENT ON COLUMN trisano.dw_contact_hospitals_view.discharge_date IS '';
 COMMENT ON COLUMN trisano.dw_contact_hospitals_view.dw_contact_events_id IS '';
 COMMENT ON COLUMN trisano.dw_contact_hospitals_view.hospital_name IS '';
 COMMENT ON COLUMN trisano.dw_contact_hospitals_view.hospital_record_number IS '';
 COMMENT ON COLUMN trisano.dw_contact_hospitals_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_contact_hospitals_view.medical_record_number IS '';
 COMMENT ON VIEW trisano.dw_contact_jurisdictions_view IS 'Jurisdictions related to contact events';
 COMMENT ON COLUMN trisano.dw_contact_jurisdictions_view.created_at IS '';
 COMMENT ON COLUMN trisano.dw_contact_jurisdictions_view.entity_id IS '';
 COMMENT ON COLUMN trisano.dw_contact_jurisdictions_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_contact_jurisdictions_view.name IS '';
 COMMENT ON COLUMN trisano.dw_contact_jurisdictions_view.short_name IS '';
 COMMENT ON COLUMN trisano.dw_contact_jurisdictions_view.updated_at IS '';
 COMMENT ON VIEW trisano.dw_contact_lab_results_view IS 'Lab results for contact events. See lab results view for more information';
 COMMENT ON COLUMN trisano.dw_contact_lab_results_view.collection_date IS '';
 COMMENT ON COLUMN trisano.dw_contact_lab_results_view.dw_contact_events_id IS '';
 COMMENT ON COLUMN trisano.dw_contact_lab_results_view.dw_encounter_events_id IS '';
 COMMENT ON COLUMN trisano.dw_contact_lab_results_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_contact_lab_results_view.interpretation IS '';
 COMMENT ON COLUMN trisano.dw_contact_lab_results_view.lab_result_text IS '';
 COMMENT ON COLUMN trisano.dw_contact_lab_results_view.lab_test_date IS '';
 COMMENT ON COLUMN trisano.dw_contact_lab_results_view.lab_type IS '';
 COMMENT ON COLUMN trisano.dw_contact_lab_results_view.name IS '';
 COMMENT ON COLUMN trisano.dw_contact_lab_results_view.reference_range IS '';
 COMMENT ON COLUMN trisano.dw_contact_lab_results_view.specimen_sent_to_uphl IS '';
 COMMENT ON COLUMN trisano.dw_contact_lab_results_view.specimen_source IS '';
 COMMENT ON COLUMN trisano.dw_contact_lab_results_view.test_detail IS '';
 COMMENT ON COLUMN trisano.dw_contact_lab_results_view.test_type IS '';
 COMMENT ON VIEW trisano.dw_contact_patients_races_view IS 'Races of patients involved in contact events. See patients_races table for more information';
 COMMENT ON COLUMN trisano.dw_contact_patients_races_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_contact_patients_races_view.person_id IS '';
 COMMENT ON COLUMN trisano.dw_contact_patients_races_view.race IS '';
 COMMENT ON VIEW trisano.dw_contact_patients_view IS 'Patients involved in contact events. See people table for more information';
 COMMENT ON COLUMN trisano.dw_contact_patients_view.birth_date IS '';
 COMMENT ON COLUMN trisano.dw_contact_patients_view.birth_gender IS '';
 COMMENT ON COLUMN trisano.dw_contact_patients_view.date_of_death IS '';
 COMMENT ON COLUMN trisano.dw_contact_patients_view.entity_id IS '';
 COMMENT ON COLUMN trisano.dw_contact_patients_view.ethnicity IS '';
 COMMENT ON COLUMN trisano.dw_contact_patients_view.first_name IS '';
 COMMENT ON COLUMN trisano.dw_contact_patients_view.first_name_soundex IS '';
 COMMENT ON COLUMN trisano.dw_contact_patients_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_contact_patients_view.last_name IS '';
 COMMENT ON COLUMN trisano.dw_contact_patients_view.last_name_soundex IS '';
 COMMENT ON COLUMN trisano.dw_contact_patients_view.middle_name IS '';
 COMMENT ON COLUMN trisano.dw_contact_patients_view.primary_language IS '';
 COMMENT ON VIEW trisano.dw_contact_questions_view IS 'Questions on forms related to contact events. See questions table for more information';
 COMMENT ON COLUMN trisano.dw_contact_questions_view.core_data IS '';
 COMMENT ON COLUMN trisano.dw_contact_questions_view.core_data_attr IS '';
 COMMENT ON COLUMN trisano.dw_contact_questions_view.created_at IS '';
 COMMENT ON COLUMN trisano.dw_contact_questions_view.data_type IS '';
 COMMENT ON COLUMN trisano.dw_contact_questions_view.form_element_id IS '';
 COMMENT ON COLUMN trisano.dw_contact_questions_view.help_text IS '';
 COMMENT ON COLUMN trisano.dw_contact_questions_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_contact_questions_view.is_required IS '';
 COMMENT ON COLUMN trisano.dw_contact_questions_view.question_text IS '';
 COMMENT ON COLUMN trisano.dw_contact_questions_view.short_name IS '';
 COMMENT ON COLUMN trisano.dw_contact_questions_view.size IS '';
 COMMENT ON COLUMN trisano.dw_contact_questions_view.style IS '';
 COMMENT ON COLUMN trisano.dw_contact_questions_view.updated_at IS '';
 COMMENT ON VIEW trisano.dw_contact_secondary_jurisdictions_view IS 'Secondary jurisdictions of contact events';
 COMMENT ON COLUMN trisano.dw_contact_secondary_jurisdictions_view.dw_contact_events_id IS '';
 COMMENT ON COLUMN trisano.dw_contact_secondary_jurisdictions_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_contact_secondary_jurisdictions_view.jurisdiction_id IS 'Places record related to this jurisdiction';
 COMMENT ON COLUMN trisano.dw_contact_secondary_jurisdictions_view.name IS 'Name of the jurisdiction';
 COMMENT ON VIEW trisano.dw_contact_treatments_events_view IS 'Treatment events related to contact events. See treatment_events table for more information';
 COMMENT ON COLUMN trisano.dw_contact_treatments_events_view.date_of_treatment IS '';
 COMMENT ON COLUMN trisano.dw_contact_treatments_events_view.dw_contact_events_id IS '';
 COMMENT ON COLUMN trisano.dw_contact_treatments_events_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_contact_treatments_events_view.treatment_given IS '';
 COMMENT ON COLUMN trisano.dw_contact_treatments_events_view.treatment_id IS '';
 COMMENT ON COLUMN trisano.dw_contact_treatments_events_view.treatment_notes IS '';
 COMMENT ON VIEW trisano.dw_contact_treatments_view IS 'Treatments related to contact events. See treatments table for more information';
 COMMENT ON COLUMN trisano.dw_contact_treatments_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_contact_treatments_view.treatment_name IS '';
 COMMENT ON COLUMN trisano.dw_contact_treatments_view.treatment_type_id IS '';
 COMMENT ON VIEW trisano.dw_date_dimension_view IS 'Dates used in various records. This provides functionality for the date-related dimensions in the OLAP system';
 COMMENT ON COLUMN trisano.dw_date_dimension_view.day_of_month IS '';
 COMMENT ON COLUMN trisano.dw_date_dimension_view.day_of_week IS '';
 COMMENT ON COLUMN trisano.dw_date_dimension_view.day_of_year IS '';
 COMMENT ON COLUMN trisano.dw_date_dimension_view.fulldate IS '';
 COMMENT ON COLUMN trisano.dw_date_dimension_view.month IS '';
 COMMENT ON COLUMN trisano.dw_date_dimension_view.quarter IS '';
 COMMENT ON COLUMN trisano.dw_date_dimension_view.week_of_year IS '';
 COMMENT ON COLUMN trisano.dw_date_dimension_view.year IS '';
 COMMENT ON VIEW trisano.dw_encounter_answers_view IS 'Formbuilder answers provided in relation to encounter events. See answers table for more information';
 COMMENT ON COLUMN trisano.dw_encounter_answers_view.code IS '';
 COMMENT ON COLUMN trisano.dw_encounter_answers_view.event_id IS '';
 COMMENT ON COLUMN trisano.dw_encounter_answers_view.export_conversion_value_id IS '';
 COMMENT ON COLUMN trisano.dw_encounter_answers_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_encounter_answers_view.question_id IS '';
 COMMENT ON COLUMN trisano.dw_encounter_answers_view.text_answer IS '';
 COMMENT ON VIEW trisano.dw_encounter_patients_view IS 'Patients involved in encounter events. See people table for more information';
 COMMENT ON COLUMN trisano.dw_encounter_patients_view.birth_date IS '';
 COMMENT ON COLUMN trisano.dw_encounter_patients_view.birth_gender IS '';
 COMMENT ON COLUMN trisano.dw_encounter_patients_view.date_of_death IS '';
 COMMENT ON COLUMN trisano.dw_encounter_patients_view.entity_id IS '';
 COMMENT ON COLUMN trisano.dw_encounter_patients_view.ethnicity IS '';
 COMMENT ON COLUMN trisano.dw_encounter_patients_view.first_name IS '';
 COMMENT ON COLUMN trisano.dw_encounter_patients_view.first_name_soundex IS '';
 COMMENT ON COLUMN trisano.dw_encounter_patients_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_encounter_patients_view.last_name IS '';
 COMMENT ON COLUMN trisano.dw_encounter_patients_view.last_name_soundex IS '';
 COMMENT ON COLUMN trisano.dw_encounter_patients_view.middle_name IS '';
 COMMENT ON COLUMN trisano.dw_encounter_patients_view.primary_language IS '';
 COMMENT ON VIEW trisano.dw_encounter_questions_view IS 'Questions asked on forms for encounter events. See questions table for more information';
 COMMENT ON COLUMN trisano.dw_encounter_questions_view.core_data IS '';
 COMMENT ON COLUMN trisano.dw_encounter_questions_view.core_data_attr IS '';
 COMMENT ON COLUMN trisano.dw_encounter_questions_view.created_at IS '';
 COMMENT ON COLUMN trisano.dw_encounter_questions_view.data_type IS '';
 COMMENT ON COLUMN trisano.dw_encounter_questions_view.form_element_id IS '';
 COMMENT ON COLUMN trisano.dw_encounter_questions_view.help_text IS '';
 COMMENT ON COLUMN trisano.dw_encounter_questions_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_encounter_questions_view.is_required IS '';
 COMMENT ON COLUMN trisano.dw_encounter_questions_view.question_text IS '';
 COMMENT ON COLUMN trisano.dw_encounter_questions_view.short_name IS '';
 COMMENT ON COLUMN trisano.dw_encounter_questions_view.size IS '';
 COMMENT ON COLUMN trisano.dw_encounter_questions_view.style IS '';
 COMMENT ON COLUMN trisano.dw_encounter_questions_view.updated_at IS '';
 COMMENT ON VIEW trisano.dw_encounters_lab_results_view IS 'Lab results for encounter events. See lab_results table for more information';
 COMMENT ON COLUMN trisano.dw_encounters_lab_results_view.collection_date IS '';
 COMMENT ON COLUMN trisano.dw_encounters_lab_results_view.dw_encounter_events_id IS '';
 COMMENT ON COLUMN trisano.dw_encounters_lab_results_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_encounters_lab_results_view.interpretation IS '';
 COMMENT ON COLUMN trisano.dw_encounters_lab_results_view.lab_result_text IS '';
 COMMENT ON COLUMN trisano.dw_encounters_lab_results_view.lab_test_date IS '';
 COMMENT ON COLUMN trisano.dw_encounters_lab_results_view.lab_type IS '';
 COMMENT ON COLUMN trisano.dw_encounters_lab_results_view.name IS '';
 COMMENT ON COLUMN trisano.dw_encounters_lab_results_view.reference_range IS '';
 COMMENT ON COLUMN trisano.dw_encounters_lab_results_view.specimen_sent_to_uphl IS '';
 COMMENT ON COLUMN trisano.dw_encounters_lab_results_view.specimen_source IS '';
 COMMENT ON COLUMN trisano.dw_encounters_lab_results_view.test_detail IS '';
 COMMENT ON COLUMN trisano.dw_encounters_lab_results_view.test_type IS '';
 COMMENT ON VIEW trisano.dw_encounters_treatments_events_view IS 'Treatment events for encounter events. See treatment_events table for more information';
 COMMENT ON COLUMN trisano.dw_encounters_treatments_events_view.date_of_treatment IS '';
 COMMENT ON COLUMN trisano.dw_encounters_treatments_events_view.dw_encounter_events_id IS '';
 COMMENT ON COLUMN trisano.dw_encounters_treatments_events_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_encounters_treatments_events_view.treatment_given IS '';
 COMMENT ON COLUMN trisano.dw_encounters_treatments_events_view.treatment_id IS '';
 COMMENT ON COLUMN trisano.dw_encounters_treatments_events_view.treatment_notes IS '';
 COMMENT ON VIEW trisano.dw_encounters_treatments_view IS 'Treatments for encounter events. See treatments table for more information';
 COMMENT ON COLUMN trisano.dw_encounters_treatments_view.dw_encounters_id IS '';
 COMMENT ON COLUMN trisano.dw_encounters_treatments_view.dw_events_treatments_id IS '';
 COMMENT ON COLUMN trisano.dw_encounters_treatments_view.id IS 'Primary key';
 COMMENT ON VIEW trisano.dw_encounters_view IS 'Encounter events. See events table for more information, but note that many fields have been removed because they do not relate to encounter events';
 COMMENT ON COLUMN trisano.dw_encounters_view.description IS '';
 COMMENT ON COLUMN trisano.dw_encounters_view.dw_morbidity_events_id IS 'The morbidity event parent of this event';
 COMMENT ON COLUMN trisano.dw_encounters_view.encounter_date IS '';
 COMMENT ON COLUMN trisano.dw_encounters_view.encounter_event_id IS '';
 COMMENT ON COLUMN trisano.dw_encounters_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_encounters_view.investigator_id IS 'Users table record containing the investigator for this event';
 COMMENT ON COLUMN trisano.dw_encounters_view.location IS '';
 COMMENT ON VIEW trisano.dw_events_diagnostic_facilities_view IS 'Diagnostic facilities for various event types';
 COMMENT ON COLUMN trisano.dw_events_diagnostic_facilities_view.dw_contact_events_id IS 'Contact event ID, if any, related to this diagnostic facility';
 COMMENT ON COLUMN trisano.dw_events_diagnostic_facilities_view.dw_morbidity_events_id IS 'Morbidity event ID, if any, related to this diagnostic facility';
 COMMENT ON COLUMN trisano.dw_events_diagnostic_facilities_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_events_diagnostic_facilities_view.name IS 'Name of the diagnostic facility';
 COMMENT ON COLUMN trisano.dw_events_diagnostic_facilities_view.place_id IS 'Place record for this facility';
 COMMENT ON COLUMN trisano.dw_events_diagnostic_facilities_view.place_type IS 'Type of facility';
 COMMENT ON VIEW trisano.dw_events_hospitals_view IS 'Hospitalizations related to various events';
 COMMENT ON COLUMN trisano.dw_events_hospitals_view.admission_date IS '';
 COMMENT ON COLUMN trisano.dw_events_hospitals_view.discharge_date IS '';
 COMMENT ON COLUMN trisano.dw_events_hospitals_view.dw_contact_events_id IS 'Contact event ID, if any, related to this diagnostic facility';
 COMMENT ON COLUMN trisano.dw_events_hospitals_view.dw_morbidity_events_id IS 'Morbidity event ID, if any, related to this diagnostic facility';
 COMMENT ON COLUMN trisano.dw_events_hospitals_view.hospital_name IS '';
 COMMENT ON COLUMN trisano.dw_events_hospitals_view.hospital_record_number IS '';
 COMMENT ON COLUMN trisano.dw_events_hospitals_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_events_hospitals_view.medical_record_number IS '';
 COMMENT ON VIEW trisano.dw_events_reporters_view IS 'Reporters for various event types';
 COMMENT ON COLUMN trisano.dw_events_reporters_view.dw_contact_events_id IS 'Contact event ID, if any, related to this diagnostic facility';
 COMMENT ON COLUMN trisano.dw_events_reporters_view.dw_morbidity_events_id IS 'Morbidity event ID, if any, related to this diagnostic facility';
 COMMENT ON COLUMN trisano.dw_events_reporters_view.first_name IS '';
 COMMENT ON COLUMN trisano.dw_events_reporters_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_events_reporters_view.last_name IS '';
 COMMENT ON COLUMN trisano.dw_events_reporters_view.middle_name IS '';
 COMMENT ON VIEW trisano.dw_events_reporting_agencies_view IS 'Reporting agencies for various event types';
 COMMENT ON COLUMN trisano.dw_events_reporting_agencies_view.dw_contact_events_id IS 'Contact event ID, if any, related to this diagnostic facility';
 COMMENT ON COLUMN trisano.dw_events_reporting_agencies_view.dw_morbidity_events_id IS 'Morbidity event ID, if any, related to this diagnostic facility';
 COMMENT ON COLUMN trisano.dw_events_reporting_agencies_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_events_reporting_agencies_view.name IS '';
 COMMENT ON COLUMN trisano.dw_events_reporting_agencies_view.place_id IS '';
 COMMENT ON COLUMN trisano.dw_events_reporting_agencies_view.place_type IS '';
 COMMENT ON VIEW trisano.dw_events_treatments_view IS 'Treatments events related to morbidity, encounter, or contact events';
 COMMENT ON COLUMN trisano.dw_events_treatments_view.date_of_treatment IS '';
 COMMENT ON COLUMN trisano.dw_events_treatments_view.dw_contact_events_id IS 'Contact event ID, if any, related to this diagnostic facility';
 COMMENT ON COLUMN trisano.dw_events_treatments_view.dw_encounter_events_id IS 'Encounter event ID, if any, related to this diagnostic facility';
 COMMENT ON COLUMN trisano.dw_events_treatments_view.dw_morbidity_events_id IS 'Morbidity event ID, if any, related to this diagnostic facility';
 COMMENT ON COLUMN trisano.dw_events_treatments_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_events_treatments_view.treatment_given IS '';
 COMMENT ON COLUMN trisano.dw_events_treatments_view.treatment_id IS '';
 COMMENT ON COLUMN trisano.dw_events_treatments_view.treatment_notes IS '';
 COMMENT ON VIEW trisano.dw_lab_results_view IS 'Lab result records for various event types. See lab results table for more information';
 COMMENT ON COLUMN trisano.dw_lab_results_view.collection_date IS '';
 COMMENT ON COLUMN trisano.dw_lab_results_view.dw_contact_events_id IS 'Contact event ID, if any, related to this diagnostic facility';
 COMMENT ON COLUMN trisano.dw_lab_results_view.dw_encounter_events_id IS 'Encounter event ID, if any, related to this diagnostic facility';
 COMMENT ON COLUMN trisano.dw_lab_results_view.dw_morbidity_events_id IS 'Morbidity event ID, if any, related to this diagnostic facility';
 COMMENT ON COLUMN trisano.dw_lab_results_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_lab_results_view.interpretation IS '';
 COMMENT ON COLUMN trisano.dw_lab_results_view.lab_result_text IS '';
 COMMENT ON COLUMN trisano.dw_lab_results_view.lab_test_date IS '';
 COMMENT ON COLUMN trisano.dw_lab_results_view.lab_type IS '';
 COMMENT ON COLUMN trisano.dw_lab_results_view.name IS '';
 COMMENT ON COLUMN trisano.dw_lab_results_view.reference_range IS '';
 COMMENT ON COLUMN trisano.dw_lab_results_view.specimen_sent_to_uphl IS '';
 COMMENT ON COLUMN trisano.dw_lab_results_view.specimen_source IS '';
 COMMENT ON COLUMN trisano.dw_lab_results_view.test_detail IS '';
 COMMENT ON COLUMN trisano.dw_lab_results_view.test_type IS '';
 COMMENT ON VIEW trisano.dw_morbidity_answers_view IS 'Formbuild answers related to morbidity events. See answers table for more information';
 COMMENT ON COLUMN trisano.dw_morbidity_answers_view.code IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_answers_view.event_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_answers_view.export_conversion_value_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_answers_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_morbidity_answers_view.question_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_answers_view.text_answer IS '';
 COMMENT ON VIEW trisano.dw_morbidity_clinicians_view IS 'Clinicians related to morbidity events';
 COMMENT ON COLUMN trisano.dw_morbidity_clinicians_view.dw_morbidity_events_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_clinicians_view.first_name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_clinicians_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_morbidity_clinicians_view.last_name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_clinicians_view.middle_name IS '';
 COMMENT ON VIEW trisano.dw_morbidity_diagnostic_facilities_view IS 'Diagnostic facilities asscoiated with morbidity events';
 COMMENT ON COLUMN trisano.dw_morbidity_diagnostic_facilities_view.dw_morbidity_events_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_diagnostic_facilities_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_morbidity_diagnostic_facilities_view.name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_diagnostic_facilities_view.place_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_diagnostic_facilities_view.place_type IS '';
 COMMENT ON VIEW trisano.dw_morbidity_diseases_view IS 'Diseases related to morbidity events. See diseases table for more information';
 COMMENT ON COLUMN trisano.dw_morbidity_diseases_view.active IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_diseases_view.cdc_code IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_diseases_view.contact_lead_in IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_diseases_view.disease_name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_diseases_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_morbidity_diseases_view.place_lead_in IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_diseases_view.treatment_lead_in IS '';
 COMMENT ON VIEW trisano.dw_morbidity_events_view IS 'Morbidity event records. See events table for more information';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.actual_age_at_onset IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.actual_age_type IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.acuity IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.additional_risk_factors IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.age_in_years IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.city IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.contact_type_if_once_a_contact IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.county IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.date_created IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.date_deleted IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.date_disease_diagnosed IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.date_disease_onset IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.date_entered_into_system IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.date_investigation_completed IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.date_investigation_started IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.date_reported_to_public_health IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.date_updated IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.day_care_association IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.disease_event_died IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.disease_event_hospitalized IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.disease_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.disposition_if_once_a_contact IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.dw_patients_id IS 'Patient record for this event';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.estimated_age_at_onset IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.estimated_age_type IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.event_name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.event_queue_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.food_handler IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.group_living IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.healthcare_worker IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.ibis_updated_at IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.imported_from_code IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.investigating_jurisdiction IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.investigating_jurisdiction_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.investigator IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.jurisdiction_of_residence IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.jurisdiction_of_residence_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.latitude IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.lhd_case_status_code IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.longitude IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.mmwr_week IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.mmwr_year IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.occupation IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.other_data_1 IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.other_data_2 IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.outbreak_associated_code IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.outbreak_name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.parent_guardian IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.parent_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.postal_code IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.pregnancy_due_date IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.pregnant IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.record_number IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.results_reported_to_clinician_date IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.review_completed_by_state_date IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.risk_factor_details IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.sent_to_cdc IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.sent_to_ibis IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.state IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.state_case_status_code IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.street_name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.street_number IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_events_view.unit_number IS '';
 COMMENT ON VIEW trisano.dw_morbidity_hospitals_view IS 'Hospitalizations related to morbidity events';
 COMMENT ON COLUMN trisano.dw_morbidity_hospitals_view.admission_date IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_hospitals_view.discharge_date IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_hospitals_view.dw_contact_events_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_hospitals_view.dw_morbidity_events_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_hospitals_view.hospital_name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_hospitals_view.hospital_record_number IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_hospitals_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_morbidity_hospitals_view.medical_record_number IS '';
 COMMENT ON VIEW trisano.dw_morbidity_jurisdictions_view IS 'Jurisdictions of morbidity events';
 COMMENT ON COLUMN trisano.dw_morbidity_jurisdictions_view.created_at IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_jurisdictions_view.entity_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_jurisdictions_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_morbidity_jurisdictions_view.name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_jurisdictions_view.short_name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_jurisdictions_view.updated_at IS '';
 COMMENT ON VIEW trisano.dw_morbidity_lab_results_view IS 'Lab results for morbidity events. See lab_results table for more infomrmation';
 COMMENT ON COLUMN trisano.dw_morbidity_lab_results_view.collection_date IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_lab_results_view.dw_contact_events_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_lab_results_view.dw_morbidity_events_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_lab_results_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_morbidity_lab_results_view.interpretation IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_lab_results_view.lab_result_text IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_lab_results_view.lab_test_date IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_lab_results_view.lab_type IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_lab_results_view.name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_lab_results_view.reference_range IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_lab_results_view.specimen_sent_to_uphl IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_lab_results_view.specimen_source IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_lab_results_view.test_detail IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_lab_results_view.test_type IS '';
 COMMENT ON VIEW trisano.dw_morbidity_patients_races_view IS 'Races of patients in morbidity events';
 COMMENT ON COLUMN trisano.dw_morbidity_patients_races_view.id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_patients_races_view.person_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_patients_races_view.race IS '';
 COMMENT ON VIEW trisano.dw_morbidity_patients_view IS 'Patients associated with morbidity events. See people table for more information';
 COMMENT ON COLUMN trisano.dw_morbidity_patients_view.birth_date IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_patients_view.birth_gender IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_patients_view.date_of_death IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_patients_view.entity_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_patients_view.ethnicity IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_patients_view.first_name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_patients_view.first_name_soundex IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_patients_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_morbidity_patients_view.last_name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_patients_view.last_name_soundex IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_patients_view.middle_name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_patients_view.primary_language IS '';
 COMMENT ON VIEW trisano.dw_morbidity_questions_view IS 'Formbuilder questions related to morbidity events. See questions table for more information';
 COMMENT ON COLUMN trisano.dw_morbidity_questions_view.core_data IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_questions_view.core_data_attr IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_questions_view.created_at IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_questions_view.data_type IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_questions_view.form_element_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_questions_view.help_text IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_questions_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_morbidity_questions_view.is_required IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_questions_view.question_text IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_questions_view.short_name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_questions_view.size IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_questions_view.style IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_questions_view.updated_at IS '';
 COMMENT ON VIEW trisano.dw_morbidity_reporters_view IS 'Reporter records for morbidity events';
 COMMENT ON COLUMN trisano.dw_morbidity_reporters_view.dw_morbidity_events_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_reporters_view.first_name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_reporters_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_morbidity_reporters_view.last_name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_reporters_view.middle_name IS '';
 COMMENT ON VIEW trisano.dw_morbidity_reporting_agencies_view IS 'Reporting agencies for morbidity events';
 COMMENT ON COLUMN trisano.dw_morbidity_reporting_agencies_view.dw_morbidity_events_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_reporting_agencies_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_morbidity_reporting_agencies_view.name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_reporting_agencies_view.place_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_reporting_agencies_view.place_type IS '';
 COMMENT ON VIEW trisano.dw_morbidity_secondary_jurisdictions_view IS 'Secondary jurisdictions for morbidity events';
 COMMENT ON COLUMN trisano.dw_morbidity_secondary_jurisdictions_view.dw_morbidity_events_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_secondary_jurisdictions_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_morbidity_secondary_jurisdictions_view.jurisdiction_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_secondary_jurisdictions_view.name IS '';
 COMMENT ON VIEW trisano.dw_morbidity_treatments_events_view IS 'Treatment events for morbidity events';
 COMMENT ON COLUMN trisano.dw_morbidity_treatments_events_view.date_of_treatment IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_treatments_events_view.dw_morbidity_events_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_treatments_events_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_morbidity_treatments_events_view.treatment_given IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_treatments_events_view.treatment_id IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_treatments_events_view.treatment_notes IS '';
 COMMENT ON VIEW trisano.dw_morbidity_treatments_view IS 'Treatments related to morbidity events';
 COMMENT ON COLUMN trisano.dw_morbidity_treatments_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_morbidity_treatments_view.treatment_name IS '';
 COMMENT ON COLUMN trisano.dw_morbidity_treatments_view.treatment_type_id IS '';
 COMMENT ON VIEW trisano.dw_patients_races_view IS 'Races of patients';
 COMMENT ON COLUMN trisano.dw_patients_races_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_patients_races_view.person_id IS '';
 COMMENT ON COLUMN trisano.dw_patients_races_view.race IS '';
 COMMENT ON VIEW trisano.dw_place_answers_view IS 'Answers to formbuilder questions related to place events. See answers table for more information';
 COMMENT ON COLUMN trisano.dw_place_answers_view.code IS '';
 COMMENT ON COLUMN trisano.dw_place_answers_view.event_id IS '';
 COMMENT ON COLUMN trisano.dw_place_answers_view.export_conversion_value_id IS '';
 COMMENT ON COLUMN trisano.dw_place_answers_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_place_answers_view.question_id IS '';
 COMMENT ON COLUMN trisano.dw_place_answers_view.text_answer IS '';
 COMMENT ON VIEW trisano.dw_place_events_view IS 'Place events. See events table for more information, keeping in mind that many fields have been removed';
 COMMENT ON COLUMN trisano.dw_place_events_view.city IS '';
 COMMENT ON COLUMN trisano.dw_place_events_view.county IS '';
 COMMENT ON COLUMN trisano.dw_place_events_view.dw_morbidity_events_id IS 'Morbidity event record that is the parent for this record';
 COMMENT ON COLUMN trisano.dw_place_events_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_place_events_view.latitude IS '';
 COMMENT ON COLUMN trisano.dw_place_events_view.longitude IS '';
 COMMENT ON COLUMN trisano.dw_place_events_view.name IS '';
 COMMENT ON COLUMN trisano.dw_place_events_view.place_type IS '';
 COMMENT ON COLUMN trisano.dw_place_events_view.postal_code IS '';
 COMMENT ON COLUMN trisano.dw_place_events_view.state IS '';
 COMMENT ON COLUMN trisano.dw_place_events_view.street_name IS '';
 COMMENT ON COLUMN trisano.dw_place_events_view.street_number IS '';
 COMMENT ON COLUMN trisano.dw_place_events_view.unit_number IS '';
 COMMENT ON VIEW trisano.dw_place_questions_view IS 'Formbuilder questions related to place events. See questions table for more information';
 COMMENT ON COLUMN trisano.dw_place_questions_view.core_data IS '';
 COMMENT ON COLUMN trisano.dw_place_questions_view.core_data_attr IS '';
 COMMENT ON COLUMN trisano.dw_place_questions_view.created_at IS '';
 COMMENT ON COLUMN trisano.dw_place_questions_view.data_type IS '';
 COMMENT ON COLUMN trisano.dw_place_questions_view.form_element_id IS '';
 COMMENT ON COLUMN trisano.dw_place_questions_view.help_text IS '';
 COMMENT ON COLUMN trisano.dw_place_questions_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_place_questions_view.is_required IS '';
 COMMENT ON COLUMN trisano.dw_place_questions_view.question_text IS '';
 COMMENT ON COLUMN trisano.dw_place_questions_view.short_name IS '';
 COMMENT ON COLUMN trisano.dw_place_questions_view.size IS '';
 COMMENT ON COLUMN trisano.dw_place_questions_view.style IS '';
 COMMENT ON COLUMN trisano.dw_place_questions_view.updated_at IS '';
 COMMENT ON VIEW trisano.dw_secondary_jurisdictions_view IS 'Secondary jurisdictions for various event typesj';
 COMMENT ON COLUMN trisano.dw_secondary_jurisdictions_view.dw_contact_events_id IS '';
 COMMENT ON COLUMN trisano.dw_secondary_jurisdictions_view.dw_morbidity_events_id IS '';
 COMMENT ON COLUMN trisano.dw_secondary_jurisdictions_view.id IS 'Primary key';
 COMMENT ON COLUMN trisano.dw_secondary_jurisdictions_view.jurisdiction_id IS '';
 COMMENT ON COLUMN trisano.dw_secondary_jurisdictions_view.name IS '';
 COMMENT ON VIEW trisano.email_addresses_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.encounters_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.entities_view IS 'data dictionary ignore';
 COMMENT ON TABLE trisano.etl_success IS 'Internal - records results of ETL processes';
 COMMENT ON VIEW trisano.event_queues_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.events_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.export_columns_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.export_conversion_values_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.export_disease_groups_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.export_names_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.external_codes_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.form_elements_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.form_references_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.forms_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.hospitals_participations_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.lab_results_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.notes_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.participations_contacts_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.participations_encounters_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.participations_places_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.participations_risk_factors_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.participations_treatments_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.participations_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.people_races_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.people_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.places_types_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.places_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.privileges_roles_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.privileges_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.questions_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.role_memberships_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.roles_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.schema_migrations_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.staged_messages_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.tasks_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.telephones_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.treatments_view IS 'data dictionary ignore';
 COMMENT ON VIEW trisano.users_view IS 'data dictionary ignore';
 COMMENT ON SCHEMA warehouse_a IS 'Holds the actual warehouse data. data dictionary ignore';
 COMMENT ON SCHEMA warehouse_b IS 'Holds the actual warehouse data. data dictionary ignore';
